name: Deploy React App to HostGator

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ ftp.jonasiattorneys.com }}
          username: ${{ jonasiata@jonasiattorneys.com }}
          password: ${{ winston28monalisah1997 }}
          port: ${{ 21 }}
          local-dir: build/
          server-dir: public_html/
